### ISSUE TITLE
Bug in Receive routine

### ISSUE THREAD

**Issue by awardblvr** [DougC/arduino-x10#3]
In the  x10::init() function, 
Code:

  // Set I/O modes:
  pinMode(this->zeroCrossingPin, INPUT);
  pinMode(this->dataPin, OUTPUT);
  digitalWrite(this->zeroCrossingPin, HIGH); 

This is apparently the OLD style of handling configing I/O as inputs with pullups.  It places zeroCrossingPin to be in input mode and then the digitalWrite(, HIGH) turns on the input pull up resistor on.

But then later, 
Code:

  if (rp>0) {
    pinMode(rcve_pin,INPUT);             // receive X10 commands - low = 1
    pinMode(zcross_pin,INPUT);           // zero crossing - 60 Hz square wave

This has the effect of RESETTING the previous digitalWrite(, HIGH) to OFF and therefore No pullup applied.
First, it is a bug to have the pinMode() for that same pin twice. But, worse to do it the second time without the corresponding
digitalWrite(, HIGH).  Really the right way would be to do it ONCE and use the pinMode(, INPUT_PULLUP) which does both steps at once., and to only have that in once place.

**Comment by canidorichard** [comment]
I have just checked and code was changed to only set the pin mode once and use INPUT_PULLUP to enable the internal pull up resistor so now closing.
